export const metadata = {
  title: "MUAKYUNG | A Hybrid Space",
  description:
    "MUAKYUNG is a hybrid space of living, creating, gathering, and publishing — in nature.",

  openGraph: {
    title: "MUAKYUNG",
    description:
      "A hybrid space of home, studio, garden, gathering, and publishing.",
    url: "https://muakyung.com",
    siteName: "MUAKYUNG",
    images: [
      {
        url: "https://muakyung.com/og.jpg",
        width: 1200,
        height: 630,
        alt: "MUAKYUNG",
      },
    ],
    locale: "ko_KR",
    type: "website",
  },
};
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
